version: "3"
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - /home/ubuntu/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: P4sw0rd@langsungjalan.com
      MYSQL_USER: developer
      MYSQL_PASSWORD: P4sw0rd@langsungjalan.com
      MYSQL_DATABASE: langsungjalan_db
      # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # MYSQL_DATABASE: ${MYSQL_ROOT_PASSWORD}
  redis:
    image: redis:5.0
    ports:
      - 6379:6379

  mongo:
    image: mongo:4.2.6-bionic
    restart: unless-stopped
    volumes:
      - /home/ubuntu/volumes/mongo:/data/db
    ports:
      - 27017:27017

  api:
    build: ./api
    depends_on:
      - mysql
      - redis
    ports:
      - "4444:4444"

  microservice:
    build: ./microservice
    depends_on:
      - mongo
    ports:
      - "12000:12000"
